### ISSUE TITLE
PettingZoo error on validation

### ISSUE THREAD

**Issue by Logan9312** [Lux-AI-Challenge/Lux-Design-2022#69]
I'm not sure if this is a lux AI bug or a pettingzoo, but when I attempt to run the validate code to make sure everything is installed correctly, I'm met with an error.

I have tried uninstalling and reinstalling pettingzoo with no success

Code:
`luxai2022 my_bot/main.py my_other_bot/main.py -v 2 -o replay.json`

Error:
```py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Scripts\luxai2022.exe\__main__.py", line 4, in <module>
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai_runner\cli.py", line 3, in <module>
    from luxai_runner.bot import Bot
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai_runner\bot.py", line 9, in <module>
    from luxai_runner.logger import Logger
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai_runner\logger.py", line 3, in <module>
    from luxai2022.globals import TERM_COLORS
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai2022\__init__.py", line 1, in <module>
    from .env import LuxAI2022
  File "C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\luxai2022\env.py", line 7, in <module>
    from pettingzoo import ParallelEnv
ImportError: cannot import name 'ParallelEnv' from 'pettingzoo' (C:\Users\lgntr\AppData\Local\Programs\Python\Python311\Lib\site-packages\pettingzoo\__init__.py)
```

**Comment by Logan9312** [comment]
Reopening this. It seems to be an issue with python 3.11

**Comment by StoneT2000** [comment]
Yep its exactly that. Farama people just told me too in discord that they didn't test 3.11 so don't use 3.11

**Comment by ppierrep** [comment]
It seems that i encounter this error using 3.8 or 3.9. Following with 3.9 
```python
luxai2022 kits/python/main.py kits/python/main.py -v 2 -o replay.json
Traceback (most recent call last):
  File "/mnt/c/Users/isefno/projects/lux-ai/.venv/bin/luxai2022", line 5, in <module>
    from luxai_runner.cli import main
  File "/mnt/c/Users/isefno/projects/lux-ai/.venv/lib/python3.9/site-packages/luxai_runner/cli.py", line 3, in <module>
    from luxai_runner.bot import Bot
  File "/mnt/c/Users/isefno/projects/lux-ai/.venv/lib/python3.9/site-packages/luxai_runner/bot.py", line 9, in <module>
    from luxai_runner.logger import Logger
  File "/mnt/c/Users/isefno/projects/lux-ai/.venv/lib/python3.9/site-packages/luxai_runner/logger.py", line 3, in <module>
    from luxai2022.globals import TERM_COLORS
  File "/mnt/c/Users/isefno/projects/lux-ai/.venv/lib/python3.9/site-packages/luxai2022/__init__.py", line 1, in <module>
    from .env import LuxAI2022
  File "/mnt/c/Users/isefno/projects/lux-ai/.venv/lib/python3.9/site-packages/luxai2022/env.py", line 7, in <module>
    from pettingzoo import ParallelEnv
ImportError: cannot import name 'ParallelEnv' from 'pettingzoo' (/mnt/c/Users/isefno/projects/lux-ai/.venv/lib/python3.9/site-packages/pettingzoo/__init__.py)
```
With a little bit of digging, it seems that with using poetry (mine being 1.2.2) the version of `pettingzoo` installed when installing luxai2022 package is `1.3.5` which is outdated. Manually installing `pettingzoo==1.22.1` solved my issues.
