### ISSUE TITLE
Mac, error verifying installation

### ISSUE THREAD

**Issue by iamsavva** [Lux-AI-Challenge/Lux-Design-2022#75]
I am running MacOS Ventura on arm64.
After running `pip3 install --upgrade luxai2022`, followed by ` luxai2022 kits/python/main.py kits/python/main.py -v 2 -o replay.json`.

I get the following error in attempting to verify:
```
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<BotProcess.start() done, defined at /Users/savva/Desktop/Codes/Lux-Design-2022/luxai_runner/process.py:33> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/Users/savva/Desktop/Codes/Lux-Design-2022/luxai_runner/process.py", line 40, in start
    self._agent_process = await asyncio.create_subprocess_exec(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1670, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/unix_events.py", line 800, in _start
    self._proc = subprocess.Popen(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<BotProcess.start() done, defined at /Users/savva/Desktop/Codes/Lux-Design-2022/luxai_runner/process.py:33> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/Users/savva/Desktop/Codes/Lux-Design-2022/luxai_runner/process.py", line 40, in start
    self._agent_process = await asyncio.create_subprocess_exec(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1670, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/unix_events.py", line 800, in _start
    self._proc = subprocess.Popen(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
Traceback (most recent call last):
  File "/opt/homebrew/bin/luxai2022", line 8, in <module>
    sys.exit(main())
  File "/Users/savva/Desktop/Codes/Lux-Design-2022/luxai_runner/cli.py", line 83, in main
    asyncio.run(eps.run())
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/savva/Desktop/Codes/Lux-Design-2022/luxai_runner/episode.py", line 109, in run
    resolved_actions = await asyncio.gather(*action_coros)
  File "/Users/savva/Desktop/Codes/Lux-Design-2022/luxai_runner/bot.py", line 54, in step
    action, stderr = await asyncio.wait_for(self.proc.write(f"{data}\n"), timeout=self.remainingOverageTime + self.time_per_step)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/savva/Desktop/Codes/Lux-Design-2022/luxai_runner/process.py", line 72, in write
    self._agent_process.stdin.write(msg.encode())
AttributeError: 'BotProcess' object has no attribute '_agent_process'
```

Would appreciate any suggestions on how to fix this! 
Other possibly relevant info: I am aliasing python to point to `/opt/homebrew/bin/python3`.

**Comment by iamsavva** [comment]
was able to resolve by setting `self.command="python3"`, though this really seems to be a hack, given that there are half a dozen of `self.command == "python` checks.

**Comment by iamsavva** [comment]
The error seems to come from the fact that [apple dropped python2 support](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python) with Ventura, so now `python` as a command doesn't even exist on the new MacOS.  `python3` can be installed with Xcode, but all of Lux code uses the `python` command.

Do you guys have an idea for a fix?
As a hacky solution, I am tempted to just replace every `python` with `python3` in my local repo.

**Comment by themmj** [comment]
An alternative workaround would be setting an alias in your terminal session like so `alias python=python3`.
If you want to have this alias in every new terminal session just add it to an appropriate profile or rc file (e.g. `.bash_profile` or `.zshrc` etc.)

**Comment by iamsavva** [comment]
@themmj, I am already aliasing `python` to `/opt/homebrew/bin/python3` in `~/.zshrc` -- not sure why it's not picking it up while running `process.py` though. same for `alias python=python3`.

Adding a symbolic link to `python3` somewhere on the path while calling it `python` did the job. For posterity, here is the specific command I used:
`sudo ln -s /opt/homebrew/bin/python3 /usr/local/bin/python`

**Comment by AxelGoarant** [comment]
What worked for us (MacOS):
First locate python3 :
`$ which python3`
→ `/usr/local/bin/python3`
Then replace the first argument by what the command returned :
`$ sudo ln -s /usr/local/bin/python3 /usr/local/bin/python`
